service: smartqr

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:         
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.articles_table}"       
custom:
  prefix: ${opt:stage, self:provider.stage}-${self:service}  
  articles_table: ${self:custom.prefix}-articles  

functions:
  articlesCreate:
    handler: articles/create.create
    events:
      - http:
          path: articles
          method: post
          cors: false
  articlesList:
    handler: articles/list.list
    events:
      - http:
          path: articles/{title}
          method: get
          cors: false                                               
resources:
  Resources:     
    articlesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:             
        TableName: ${self:custom.articles_table}
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1